app:
  name: "web_app"
  mode: "dev"
  port: 8080
log:
  level: "debug"
  filename: "web_app.log"
  MaxSize: 10
  MaxBackups: 5
  MaxAge: 30
  Compress: false
mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "golang"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  DB: 0,
  PoolSize: 100,